name: Vitale organisaties
favicon: null
layout_spectrum: 0.6811488715466112
typography_spectrum: 0.9384733631741256
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6446854823734611
  lightness: 0.9077865520957857
  saturation: 0.37645063013769686
  rhythmicContrast: 0.6357673527672887
purpose: []
